-- CREATE DATABASE
DROP DATABASE IF EXISTS Testing_System;
CREATE DATABASE IF NOT EXISTS Testing_System;
USE Testing_System;

-- CREATE TABLE Department
CREATE TABLE `Department` (
	DepartmentID 	TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	DepartmentName 	VARCHAR (30) NOT NULL UNIQUE
);

-- CREATE TABLE Positon
CREATE TABLE `Position` (
	PositionID		TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	PositionName	VARCHAR (30) NOT NULL
);

-- CREATE TABLE Account
CREATE TABLE `Account` (
	AccountID		TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	Email			VARCHAR (30) NOT NULL,
	Username		VARCHAR (30) NOT NULL,
    Fullname 		VARCHAR (30) NOT NULL,
	DepartmentID	TINYINT UNSIGNED NOT NULL,
	PositionID		TINYINT UNSIGNED NOT NULL,
	CreatDate		DATE 
);

-- CREATE TABLE Group
CREATE TABLE `Group` (
	GroupID			TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	Groupname		VARCHAR (30) NOT NULL,
	CreatorID		TINYINT UNSIGNED NOT NULL,
	CreatDate		DATE 
);

-- CREATE TABLE GroupAccount
CREATE TABLE GroupAccount (
	GroupID			TINYINT UNSIGNED NOT NULL,
	AccountID 		TINYINT UNSIGNED NOT NULL,
	Joindate		DATE 
);

-- CREATE TABLE TypeQuestion
CREATE TABLE TypeQuestion (
	TypeID 			TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	TypeName 		VARCHAR (30) NOT NULL
);

-- CREATE TABLE CategoryQuestion
CREATE TABLE CategoryQuestion (
	CategoryID		TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	CategoryName	VARCHAR (30) NOT NULL
);

-- CREATE TABLE Question
CREATE TABLE Question (
	QuestionID		TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	Content			VARCHAR (30) NOT NULL,
	CategoryID		TINYINT UNSIGNED NOT NULL,
	TypeID			TINYINT UNSIGNED NOT NULL,
	CreatorID		TINYINT UNSIGNED NOT NULL,
	CreatDate		DATE 
);

-- CREATE TABLE Answer
CREATE TABLE Answer (
	AnswerID 		TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	Content			VARCHAR (30) NOT NULL,
	QuestionID		TINYINT UNSIGNED NOT NULL,
	isCorrect 		BOOLEAN
);

-- CREATE TABLE Exam
CREATE TABLE Exam (
	ExamID 			TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`Code`			VARCHAR (30) NOT NULL,
	Title			VARCHAR (30) NOT NULL,
	CategoryID		TINYINT UNSIGNED NOT NULL,
	Duration		INT UNSIGNED NOT NULL,
	CreatorID		TINYINT UNSIGNED NOT NULL,
	CreatDate		DATE 
);

-- CREATE TABLE ExamQuestion
CREATE TABLE ExamQuestion (
	ExamID 			TINYINT UNSIGNED NOT NULL,
	QuestionID		TINYINT UNSIGNED NOT NULL
);

